### ISSUE TITLE
piping spire shell :print output to dev null results in divide by zero

### ISSUE THREAD

**Issue by retrogradeorbit** [epiccastle/spire#103]
```
spire$ lein trampoline run -- -e '(shell {:cmd "echo bar 1>&2" :print true})' 1>/dev/null
bar
Exception in thread "async-thread-macro-1" java.lang.ArithmeticException: Divide by zero
	at clojure.lang.Numbers.quotient(Numbers.java:195)
	at clojure.lang.Numbers.quotient(Numbers.java:1879)
	at spire.utils$num_terminal_lines.invokeStatic(utils.clj:399)
	at spire.utils$num_terminal_lines.invoke(utils.clj:392)
	at spire.output.default$print_state.invokeStatic(default.clj:220)
	at spire.output.default$print_state.invoke(default.clj:190)
	at spire.output.default$state_change$iter__17988__17992$fn__17993.invoke(default.clj:339)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5405.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3135)
	at clojure.core$doall.invokeStatic(core.clj:3150)
	at clojure.core$doall.invoke(core.clj:3150)
	at spire.output.default$state_change.invokeStatic(default.clj:337)
	at spire.output.default$state_change.invoke(default.clj:223)
	at spire.output.default$eval18117$fn__18118$fn__18119.invoke(default.clj:407)
	at clojure.core.async$thread_call$fn__15344.invoke(async.clj:484)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by retrogradeorbit** [comment]
fixed in v0.1.0-alpha.15
