### ISSUE TITLE
upload module doesn't preserve file attributes on single file

### ISSUE THREAD

**Issue by retrogradeorbit** [epiccastle/spire#124]
First copied file without preserving attributes:

```
     (upload {:src "/home/crispin/bin/spire"
              :dest "/usr/local/bin/spire"})
```

That worked. Then added `:preserve true`

```
     (upload {:src "/home/crispin/bin/spire"
              :dest "/usr/local/bin/spire"
              :preserve true})
```

And got:

```
provisioning/email.clj:68 (upload {:src "/home/crispin/bin/spire", :preserve true, :dest "/usr/local/bin/spire"})
Exception in thread "main" clojure.lang.ExceptionInfo: Assert failed: attribute tree must be passed a directory
(.isDirectory file) [at provisioning/email.clj, line 13, column 1] {:type :sci/error, :line 13, :column 1, :message "Assert failed: attribute tree must be passed a directory\n(.isDirectory file) [at provisioning/email.clj, line 13, column 1]"}
	at sci.impl.utils$rethrow_with_location_of_node.invokeStatic(utils.cljc:72)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:573)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:613)
	at sci.impl.interpreter$eval_form.invokeStatic(interpreter.cljc:645)
	at sci.impl.interpreter$eval_string_STAR_.invokeStatic(interpreter.cljc:658)
	at sci.core$eval_string_STAR_.invokeStatic(core.cljc:189)
	at spire.eval$evaluate.invokeStatic(eval.clj:87)
	at spire.core$_main.invokeStatic(core.clj:80)
	at spire.core$_main.doInvoke(core.clj:57)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at spire.core.main(Unknown Source)
Caused by: java.lang.AssertionError: Assert failed: attribute tree must be passed a directory
(.isDirectory file)
	at spire.module.attrs$create_attribute_list.invokeStatic(attrs.clj:72)
	at spire.module.attrs$set_attrs_preserve.invokeStatic(attrs.clj:102)
	at spire.module.upload$upload_STAR_.invokeStatic(upload.clj:303)
	at spire.module.upload$upload_STAR_.doInvoke(upload.clj:100)

```

**Comment by retrogradeorbit** [comment]
also happens on initial copy with single file and `:preserve true`
