### ISSUE TITLE
upload with sudo broken in alpha.17

### ISSUE THREAD

**Issue by hamann** [epiccastle/spire#142]
```
❯ spire --version
Version: 0.1.0-alpha.17
```

`(upload)` is broken with sudo context, but works with alpha.16 and  alpha.15

```txt
scp-to: scp   -t /etc/environment using executor :ssh
scp-to 228 bytes of content to /etc/environment
Receive initial ACK
Sent command C0644 228 environment
Exception in thread "main" clojure.lang.ExceptionInfo: scp error {:type :sci/error, :line 5, :column 1, :message "scp error", :sci.impl/callstack #object[clojure.lang.Volatile 0x44055242 {:status :ready, :val ()}], :file nil, :locals {}}
        at sci.impl.utils$rethrow_with_location_of_node.invokeStatic(utils.cljc:85)
        at sci.impl.evaluator$eval.invokeStatic(evaluator.cljc:338)
        at sci.impl.interpreter$eval_form.invokeStatic(interpreter.cljc:44)
        at sci.impl.interpreter$eval_string_STAR_.invokeStatic(interpreter.cljc:59)
        at sci.core$eval_string_STAR_.invokeStatic(core.cljc:236)
        at spire.eval$evaluate.invokeStatic(eval.clj:87)
        at spire.core$_main.invokeStatic(core.clj:85)
        at spire.core$_main.doInvoke(core.clj:59)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at spire.core.main(Unknown Source)
Caused by: clojure.lang.ExceptionInfo: scp error {:code 1, :msg "scp: /etc/environment: Permission denied"}
        at spire.scp$scp_receive_ack.invokeStatic(scp.clj:35)
        at spire.scp$scp_send_command.invokeStatic(scp.clj:48)
        at spire.scp$scp_copy_data.invokeStatic(scp.clj:116)
        at spire.scp$scp_content_to.invokeStatic(scp.clj:301)
        at spire.module.upload$upload_STAR_.invokeStatic(upload.clj:266)
        at spire.module.upload$upload_STAR_.doInvoke(upload.clj:100)
        at clojure.lang.RestFn.invoke(RestFn.java:457)
        at sci.impl.vars.SciVar.invoke(vars.cljc:329)
        at sci.impl.analyzer$return_call$fn__4047.invoke(analyzer.cljc:1040)
        at sci.impl.evaluator$eval.invokeStatic(evaluator.cljc:341)
        at sci.impl.evaluator$eval.invoke(evaluator.cljc:335)
        at sci.impl.evaluator$eval_let$fn__2090.invoke(evaluator.cljc:64)
        at sci.impl.evaluator$eval_let.invokeStatic(evaluator.cljc:57)
        at sci.impl.analyzer$expand_let_STAR_$fn__3702.invoke(analyzer.cljc:394)
        at sci.impl.evaluator$eval.invokeStatic(evaluator.cljc:341)
        at sci.impl.evaluator$eval.invoke(evaluator.cljc:335)
        at sci.impl.evaluator$eval_try.invokeStatic(evaluator.cljc:150)
        at sci.impl.analyzer$analyze_try$fn__3781.invoke(analyzer.cljc:616)
        at sci.impl.evaluator$eval.invokeStatic(evaluator.cljc:341)
        at sci.impl.analyzer$return_do$fn__3095.invoke(analyzer.cljc:115)
        at sci.impl.evaluator$eval.invokeStatic(evaluator.cljc:341)
        at sci.impl.evaluator$eval.invoke(evaluator.cljc:335)
        at sci.impl.evaluator$eval_let$fn__2090.invoke(evaluator.cljc:64)
        at sci.impl.evaluator$eval_let.invokeStatic(evaluator.cljc:57)
        at sci.impl.analyzer$expand_let_STAR_$fn__3702.invoke(analyzer.cljc:394)
        at sci.impl.evaluator$eval.invokeStatic(evaluator.cljc:341)
        at sci.impl.evaluator$eval.invoke(evaluator.cljc:335)
        at sci.impl.evaluator$eval_try.invokeStatic(evaluator.cljc:150)
        at sci.impl.analyzer$analyze_try$fn__3781.invoke(analyzer.cljc:616)
        at sci.impl.evaluator$eval.invokeStatic(evaluator.cljc:341)
        at sci.impl.evaluator$eval.invoke(evaluator.cljc:335)
        at sci.impl.evaluator$eval_let.invokeStatic(evaluator.cljc:76)
        at sci.impl.analyzer$expand_let_STAR_$fn__3702.invoke(analyzer.cljc:394)
        at sci.impl.evaluator$eval.invokeStatic(evaluator.cljc:341)
        at sci.impl.evaluator$eval.invoke(evaluator.cljc:335)
        at sci.impl.evaluator$eval_let.invokeStatic(evaluator.cljc:76)
        at sci.impl.analyzer$expand_let_STAR_$fn__3702.invoke(analyzer.cljc:394)
        at sci.impl.evaluator$eval.invokeStatic(evaluator.cljc:341)
        at sci.impl.evaluator$eval.invoke(evaluator.cljc:335)
        at sci.impl.evaluator$eval_let.invokeStatic(evaluator.cljc:76)
        at sci.impl.analyzer$expand_let_STAR_$fn__3702.invoke(analyzer.cljc:394)
        at sci.impl.evaluator$eval.invokeStatic(evaluator.cljc:341)
        at sci.impl.analyzer$return_do$fn__3095.invoke(analyzer.cljc:115)
        at sci.impl.evaluator$eval.invokeStatic(evaluator.cljc:341)
        at sci.impl.evaluator$eval.invoke(evaluator.cljc:335)
        at sci.impl.evaluator$eval_try.invokeStatic(evaluator.cljc:150)
        at sci.impl.analyzer$analyze_try$fn__3781.invoke(analyzer.cljc:616)
        at sci.impl.evaluator$eval.invokeStatic(evaluator.cljc:341)
        at sci.impl.evaluator$eval.invoke(evaluator.cljc:335)
        at sci.impl.evaluator$eval_let.invokeStatic(evaluator.cljc:76)
        at sci.impl.analyzer$expand_let_STAR_$fn__3702.invoke(analyzer.cljc:394)
        at sci.impl.evaluator$eval.invokeStatic(evaluator.cljc:341)
        at sci.impl.evaluator$eval.invoke(evaluator.cljc:335)
        at sci.impl.evaluator$eval_let.invokeStatic(evaluator.cljc:76)
        at sci.impl.analyzer$expand_let_STAR_$fn__3702.invoke(analyzer.cljc:394)
        at sci.impl.evaluator$eval.invokeStatic(evaluator.cljc:341)
        at sci.impl.evaluator$eval.invoke(evaluator.cljc:335)
        at sci.impl.evaluator$eval_try.invokeStatic(evaluator.cljc:150)
        at sci.impl.analyzer$analyze_try$fn__3781.invoke(analyzer.cljc:616)
        at sci.impl.evaluator$eval.invokeStatic(evaluator.cljc:341)
        at sci.impl.evaluator$eval.invoke(evaluator.cljc:335)
        at sci.impl.evaluator$eval_let.invokeStatic(evaluator.cljc:76)
        at sci.impl.analyzer$expand_let_STAR_$fn__3702.invoke(analyzer.cljc:394)
        at sci.impl.evaluator$eval.invokeStatic(evaluator.cljc:341)
        ... 8 more
 x

```

**Comment by retrogradeorbit** [comment]
I've replicated this. can confirm the file is being uploaded as connected user, not sudo user.

**Comment by hamann** [comment]
Can't reopen, but it still persists.
