### ISSUE TITLE
SSH broken with ubuntu jammy (22.04)

### ISSUE THREAD

**Issue by hamann** [epiccastle/spire#146]
We're preparing for the next ubuntu LTS release and realized that spire then refuses to connect.

```sh
spire --version
Version: 0.1.0-alpha.18
spire --debug-ssh foo.clj
Connecting to localhost port 54321
Connection established
Remote version string: SSH-2.0-OpenSSH_8.9p1 Ubuntu-3
Local version string: SSH-2.0-JSCH-0.1.54
CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
CheckSignatures: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
ecdsa-sha2-nistp256 is not available.
ecdsa-sha2-nistp384 is not available.
ecdsa-sha2-nistp521 is not available.
SSH_MSG_KEXINIT sent
SSH_MSG_KEXINIT received
kex: server: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,sntrup761x25519-sha512@openssh.com,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-gro
up14-sha256
kex: server: rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
kex: server: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
kex: server: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
kex: server: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
kex: server: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
kex: server: none,zlib@openssh.com
kex: server: none,zlib@openssh.com
kex: server:
kex: server:
kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
kex: client: ssh-rsa,ssh-dss
kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
kex: client: none
kex: client: none
kex: client:
kex: client:
Disconnecting from localhost port 54321
Exception in thread "main" com.jcraft.jsch.JSchException: Algorithm negotiation fail
        at com.jcraft.jsch.Session.receive_kexinit(Session.java:590)
        at com.jcraft.jsch.Session.connect(Session.java:320)
        at com.jcraft.jsch.Session.connect(Session.java:183)
        at spire.transport$connect.invokeStatic(transport.clj:34)
        at spire.transport$open_connection$fn__12318.invoke(transport.clj:56)
        at clojure.core$update.invokeStatic(core.clj:6185)
        at clojure.core$update.invoke(core.clj:6177)
        at clojure.lang.Atom.swap(Atom.java:65)
        at clojure.core$swap_BANG_.invokeStatic(core.clj:2358)
        at spire.transport$open_connection.invokeStatic(transport.clj:51)
        at spire.transport$open_connection.invoke(transport.clj:50)
        at sci.impl.vars.SciVar.invoke(vars.cljc:325)
        at sci.impl.analyzer$return_call$reify__4565.eval(analyzer.cljc:1149)
        at sci.impl.evaluator$eval_let$fn__2076.invoke(evaluator.cljc:65)
        at sci.impl.evaluator$eval_let.invokeStatic(evaluator.cljc:56)
        at sci.impl.analyzer$analyze_let_STAR_$reify__4237.eval(analyzer.cljc:492)
        at sci.impl.evaluator$eval_try.invokeStatic(evaluator.cljc:125)
        at sci.impl.analyzer$analyze_try$reify__4320.eval(analyzer.cljc:741)
        at sci.impl.evaluator$eval_let.invokeStatic(evaluator.cljc:74)
        at sci.impl.analyzer$analyze_let_STAR_$reify__4237.eval(analyzer.cljc:492)
        at sci.impl.interpreter$eval_form.invokeStatic(interpreter.cljc:39)
        at sci.impl.interpreter$eval_string_STAR_.invokeStatic(interpreter.cljc:61)
        at sci.core$eval_string_STAR_.invokeStatic(core.cljc:235)
        at spire.eval$evaluate.invokeStatic(eval.clj:87)
        at spire.core$_main.invokeStatic(core.clj:85)
        at spire.core$_main.doInvoke(core.clj:59)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at spire.core.main(Unknown Source)
```

Vagrantfile to reproduce
```txt
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "4096"
    v.vmx["numvcpus"] = "2"
  end

  config.vm.network "forwarded_port", id: "ssh", host: 54321, guest: 22
end
```

I noticed that jsch reports 0.1.54 whereas project.clj sets https://github.com/epiccastle/spire/blob/7d3ebd7d3c53a10252ac00eb38c29395e56f1e80/project.clj#L26

**Comment by retrogradeorbit** [comment]
I knew jsch was getting crufty. I didn't know there was a maintained fork!
