### ISSUE TITLE
specifying just :host-string and :identity together fails connection

### ISSUE THREAD

**Issue by retrogradeorbit** [epiccastle/spire#22]
```
spire -e '(ssh {:host-string "localhost" :identity "/home/crispin/.ssh/id_rsa"} (get-fact [:system]))'
Exception in thread "main" java.lang.NullPointerException
	at clojure.core$name.invokeStatic(core.clj:1595)
	at clojure.core$name.invoke(core.clj:1589)
	at spire.ssh$make_session.invokeStatic(ssh.clj:189)
	at spire.ssh$make_session.invoke(ssh.clj:157)
        ...
```

**Comment by retrogradeorbit** [comment]
fixed in 0.1.0-alpha.3
