### ISSUE TITLE
Invoke with MethodHandle argument could not be reduced to at most a single call or single field access.

### ISSUE THREAD

**Issue by retrogradeorbit** [epiccastle/spire#33]
```
$ spire  -e '(System/getenv "DO_TOKEN")'
Exception in thread "main" clojure.lang.ExceptionInfo: Invoke with MethodHandle argument could not be reduced to at most a single call or single field access. The method handle must be a compile time constant, e.g., be loaded from a `static final` field. Method that contains the method handle invocation: java.lang.invoke.Invokers$Holder.invoke_MT(Object, Object, Object, Object) [at line 1, column 1] {:type :sci/error, :line 1, :column 1, :message "Invoke with MethodHandle argument could not be reduced to at most a single call or single field access. The method handle must be a compile time constant, e.g., be loaded from a `static final` field. Method that contains the method handle invocation: java.lang.invoke.Invokers$Holder.invoke_MT(Object, Object, Object, Object) [at line 1, column 1]"}
	at sci.impl.utils$rethrow_with_location_of_node.invokeStatic(utils.cljc:72)
	at sci.impl.utils$rethrow_with_location_of_node.invoke(utils.cljc:56)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:479)
	at sci.impl.interpreter$eval_call.invoke(interpreter.cljc:459)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:509)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:492)
	at sci.impl.interpreter$eval_form.invokeStatic(interpreter.cljc:549)
	at sci.impl.interpreter$eval_form.invoke(interpreter.cljc:540)
	at sci.impl.interpreter$eval_string_STAR_.invokeStatic(interpreter.cljc:559)
	at sci.impl.interpreter$eval_string_STAR_.invoke(interpreter.cljc:552)
	at sci.impl.interpreter$eval_string$fn__2858.invoke(interpreter.cljc:572)
	at sci.impl.interpreter$eval_string.invokeStatic(interpreter.cljc:569)
	at sci.impl.interpreter$eval_string.invoke(interpreter.cljc:565)
	at sci.core$eval_string.invokeStatic(core.cljc:174)
	at sci.core$eval_string.invoke(core.cljc:137)
	at spire.core$evaluate.invokeStatic(core.clj:57)
	at spire.core$evaluate.invoke(core.clj:55)
	at spire.core$_main.invokeStatic(core.clj:92)
	at spire.core$_main.doInvoke(core.clj:73)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at spire.core.main(Unknown Source)
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Invoke with MethodHandle argument could not be reduced to at most a single call or single field access. The method handle must be a compile time constant, e.g., be loaded from a `static final` field. Method that contains the method handle invocation: java.lang.invoke.Invokers$Holder.invoke_MT(Object, Object, Object, Object)
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:101)
	at sci.impl.Reflector.canAccess(Reflector.java:54)
	at sci.impl.Reflector.invokeMatchingMethod(Reflector.java:161)
	at sci.impl.Reflector.invokeStaticMethod(Reflector.java:337)
	at sci.impl.interop$invoke_static_method.invokeStatic(interop.cljc:32)
	at sci.impl.interop$invoke_static_method.invoke(interop.cljc:29)
	at sci.impl.interpreter$eval_static_method_invocation.invokeStatic(interpreter.cljc:275)
	at sci.impl.interpreter$eval_static_method_invocation.invoke(interpreter.cljc:274)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:469)
	... 18 more
```

**Comment by retrogradeorbit** [comment]
fixed in 0.1.0-alpha.4
