### ISSUE TITLE
sudo assertion fails when sudo cant resolve hostname

### ISSUE THREAD

**Issue by retrogradeorbit** [epiccastle/spire#44]
```
Caused by: java.lang.AssertionError: Assert failed: Unknown response from sudo test in requires-password? exit: 0 err: "sudo: unable to resolve host epiccastle\n"
 out: "uid=0(root) gid=0(root) groups=0(root)\n"

false
	at spire.module.sudo$requires_password_QMARK_.invokeStatic(sudo.clj:107)
	at spire.module.sudo$requires_password_QMARK_.invoke(sudo.clj:86)
```

**Comment by retrogradeorbit** [comment]
fixed in 0.1.0-alpha.9
