### ISSUE TITLE
curl :method :DELETE causes NPE

### ISSUE THREAD

**Issue by retrogradeorbit** [epiccastle/spire#46]
```
./digitalocean.clj:41 (curl {:method :DELETE, :headers {:authorization (format "Bearer %s" (System/getenv "DO_TOKEN"))}, :url (format "https://api.
Exception in thread "main" java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1770)
	at java.util.regex.Matcher.reset(Matcher.java:416)
	at java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.util.regex.Pattern.matcher(Pattern.java:1133)
	at java.util.regex.Pattern.split(Pattern.java:1261)
	at java.util.regex.Pattern.split(Pattern.java:1334)
	at clojure.string$split.invokeStatic(string.clj:224)
	at clojure.string$split.invoke(string.clj:219)
	at spire.module.curl$fn__4267$fn__4268.invoke(curl.clj:143)
	at clojure.lang.MultiFn.invoke(MultiFn.java:238)
	at spire.module.curl$curl_response__GT_map.invokeStatic(curl.clj:174)
	at spire.module.curl$curl_response__GT_map.invoke(curl.clj:161)
	at spire.module.curl$process_result.invokeStatic(curl.clj:193)
	at spire.module.curl$process_result.invoke(curl.clj:181)
	at spire.module.curl$curl_STAR_.invokeStatic(curl.clj:216)
	at spire.module.curl$curl_STAR_.doInvoke(curl.clj:204)
...
```

**Comment by retrogradeorbit** [comment]
fixed in 0.1.0-alpha.9
