### ISSUE TITLE
support pem encoded identity files.

### ISSUE THREAD

**Issue by retrogradeorbit** [epiccastle/spire#48]
```
Exception in thread "main" clojure.lang.ExceptionInfo: invalid privatekey: [B@7efdf3466958 [at line 1, column 1] {:type :sci/error, :line 1, :column 1, :message "invalid privatekey: [B@7efdf3466958 [at line 1, column 1]"}
	at sci.impl.utils$rethrow_with_location_of_node.invokeStatic(utils.cljc:74)
	at sci.impl.utils$rethrow_with_location_of_node.invoke(utils.cljc:58)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:518)
	at sci.impl.interpreter$eval_call.invoke(interpreter.cljc:498)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:547)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:530)
	at sci.impl.interpreter$eval_form.invokeStatic(interpreter.cljc:588)
	at sci.impl.interpreter$eval_form.invoke(interpreter.cljc:579)
	at sci.impl.interpreter$eval_string_STAR_.invokeStatic(interpreter.cljc:598)
	at sci.impl.interpreter$eval_string_STAR_.invoke(interpreter.cljc:593)
	at sci.impl.interpreter$eval_string$fn__4572.invoke(interpreter.cljc:610)
	at sci.impl.interpreter$eval_string.invokeStatic(interpreter.cljc:607)
	at sci.impl.interpreter$eval_string.invoke(interpreter.cljc:603)
	at sci.core$eval_string.invokeStatic(core.cljc:178)
	at sci.core$eval_string.invoke(core.cljc:141)
	at spire.eval$evaluate.invokeStatic(eval.clj:71)
	at spire.eval$evaluate.invoke(eval.clj:61)
	at spire.core$_main.invokeStatic(core.clj:73)
	at spire.core$_main.doInvoke(core.clj:56)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at spire.core.main(Unknown Source)
Caused by: com.jcraft.jsch.JSchException: invalid privatekey: [B@7efdf3466958
	at com.jcraft.jsch.KeyPair.load(KeyPair.java:948)
	at com.jcraft.jsch.KeyPair.load(KeyPair.java:561)
	at com.jcraft.jsch.IdentityFile.newInstance(IdentityFile.java:40)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:406)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:366)
	at spire.ssh$make_session.invokeStatic(ssh.clj:172)
	at spire.ssh$make_session.invoke(ssh.clj:157)
	at spire.transport$connect.invokeStatic(transport.clj:19)
	at spire.transport$connect.invoke(transport.clj:15)
	at spire.transport$open_connection$fn__2208.invoke(transport.clj:45)
	at clojure.core$update.invokeStatic(core.clj:6198)
	at clojure.core$update.invoke(core.clj:6190)
	at clojure.lang.Atom.swap(Atom.java:65)
	at clojure.core$swap_BANG_.invokeStatic(core.clj:2356)
	at clojure.core$swap_BANG_.invoke(core.clj:2347)
```

**Comment by retrogradeorbit** [comment]
Pem is already supported. This error was trying to pass a public key in as a private key.
