### ISSUE TITLE
Upload not working correctly if the file doesn't exists

### ISSUE THREAD

**Issue by josesanch** [epiccastle/spire#62]
deploy.clj:94 (upload {:content "hola", :dest "test"})                                                                                                
prueba [String Data]|===============================================================================================================| 100%                         
Exception in thread "main" clojure.lang.ExceptionInfo: No matching field found: close for class java.io.PipedInputStream [at deploy.clj, line 90, column 3] {:type :sci/error, :line 90, :column 3, :message "No matching field found: close for class java.io.PipedInputStream [at deploy.clj, line 90, column 3]"}
	at sci.impl.utils$rethrow_with_location_of_node.invokeStatic(utils.cljc:74)
	at sci.impl.utils$rethrow_with_location_of_node.invoke(utils.cljc:58)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:522)
	at sci.impl.interpreter$eval_call.invoke(interpreter.cljc:502)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:551)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:534)
	at sci.impl.interpreter$eval_let.invokeStatic(interpreter.cljc:83)
	at sci.impl.interpreter$eval_let.doInvoke(interpreter.cljc:59)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:475)
	at sci.impl.interpreter$eval_special_call.invoke(interpreter.cljc:469)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:509)
	at sci.impl.interpreter$eval_call.invoke(interpreter.cljc:502)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:551)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:534)
	at sci.impl.interpreter$eval_form.invokeStatic(interpreter.cljc:592)
	at sci.impl.interpreter$eval_form.invoke(interpreter.cljc:583)
	at sci.impl.interpreter$eval_string_STAR_.invokeStatic(interpreter.cljc:603)
	at sci.impl.interpreter$eval_string_STAR_.invoke(interpreter.cljc:597)
	at sci.core$eval_string_STAR_.invokeStatic(core.cljc:193)
	at sci.core$eval_string_STAR_.invoke(core.cljc:189)
	at spire.eval$evaluate.invokeStatic(eval.clj:88)
	at spire.eval$evaluate.invoke(eval.clj:86)
	at spire.core$_main.invokeStatic(core.clj:80)
	at spire.core$_main.doInvoke(core.clj:57)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at spire.core.main(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No matching field found: close for class java.io.PipedInputStream
	at clojure.lang.Reflector.getInstanceField(Reflector.java:374)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:417)
	at spire.scp$scp_to.invokeStatic(scp.clj:255)
	at spire.scp$scp_to.doInvoke(scp.clj:212)
	at clojure.lang.RestFn.invoke(RestFn.java:3269)
	at spire.module.upload$upload_STAR_.invokeStatic(upload.clj:233)
	at spire.module.upload$upload_STAR_.doInvoke(upload.clj:100)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at sci.impl.interpreter$fn_call.invokeStatic(interpreter.cljc:467)
	at sci.impl.interpreter$fn_call.invoke(interpreter.cljc:467)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:518)
	at sci.impl.interpreter$eval_call.invoke(interpreter.cljc:502)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:551)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:534)
	at sci.impl.interpreter$eval_do_STAR_$fn__4374.invoke(interpreter.cljc:424)
	at sci.impl.interpreter$eval_do_STAR_.invokeStatic(interpreter.cljc:424)
	at sci.impl.interpreter$eval_do_STAR_.invoke(interpreter.cljc:421)
	at sci.impl.interpreter$eval_do.invokeStatic(interpreter.cljc:434)
	at sci.impl.interpreter$eval_do.invoke(interpreter.cljc:431)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:471)
	at sci.impl.interpreter$eval_special_call.invoke(interpreter.cljc:469)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:509)
	at sci.impl.interpreter$eval_call.invoke(interpreter.cljc:502)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:551)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:534)
	at sci.impl.interpreter$eval_let$fn__4211.invoke(interpreter.cljc:74)
	at sci.impl.interpreter$eval_let.invokeStatic(interpreter.cljc:62)
	at sci.impl.interpreter$eval_let.doInvoke(interpreter.cljc:59)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:475)
	at sci.impl.interpreter$eval_special_call.invoke(interpreter.cljc:469)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:509)
	at sci.impl.interpreter$eval_call.invoke(interpreter.cljc:502)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:551)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:534)
	at sci.impl.interpreter$eval_do_STAR_$fn__4374.invoke(interpreter.cljc:424)
	at sci.impl.interpreter$eval_do_STAR_.invokeStatic(interpreter.cljc:424)
	at sci.impl.interpreter$eval_do_STAR_.invoke(interpreter.cljc:421)
	at sci.impl.interpreter$eval_do.invokeStatic(interpreter.cljc:434)
	at sci.impl.interpreter$eval_do.invoke(interpreter.cljc:431)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:471)
	at sci.impl.interpreter$eval_special_call.invoke(interpreter.cljc:469)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:509)
	at sci.impl.interpreter$eval_call.invoke(interpreter.cljc:502)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:551)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:534)
	at sci.impl.interpreter$eval_try.invokeStatic(interpreter.cljc:289)
	at sci.impl.interpreter$eval_try.invoke(interpreter.cljc:284)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:552)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:534)
	at sci.impl.interpreter$eval_do_STAR_$fn__4374.invoke(interpreter.cljc:424)
	at sci.impl.interpreter$eval_do_STAR_.invokeStatic(interpreter.cljc:424)
	at sci.impl.interpreter$eval_do_STAR_.invoke(interpreter.cljc:421)
	at sci.impl.interpreter$eval_do.invokeStatic(interpreter.cljc:434)
	at sci.impl.interpreter$eval_do.invoke(interpreter.cljc:431)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:471)
	at sci.impl.interpreter$eval_special_call.invoke(interpreter.cljc:469)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:509)
	at sci.impl.interpreter$eval_call.invoke(interpreter.cljc:502)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:551)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:534)
	at sci.impl.interpreter$eval_do_STAR_$fn__4374.invoke(interpreter.cljc:424)
	at sci.impl.interpreter$eval_do_STAR_.invokeStatic(interpreter.cljc:424)
	at sci.impl.interpreter$eval_do_STAR_.invoke(interpreter.cljc:421)
	at sci.impl.interpreter$eval_do.invokeStatic(interpreter.cljc:434)
	at sci.impl.interpreter$eval_do.invoke(interpreter.cljc:431)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:471)
	at sci.impl.interpreter$eval_special_call.invoke(interpreter.cljc:469)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:509)
	at sci.impl.interpreter$eval_call.invoke(interpreter.cljc:502)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:551)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:534)
	at sci.impl.interpreter$eval_do_STAR_$fn__4374.invoke(interpreter.cljc:424)
	at sci.impl.interpreter$eval_do_STAR_.invokeStatic(interpreter.cljc:424)
	at sci.impl.interpreter$eval_do_STAR_.invoke(interpreter.cljc:421)
	at sci.impl.interpreter$eval_do.invokeStatic(interpreter.cljc:434)
	at sci.impl.interpreter$eval_do.invoke(interpreter.cljc:431)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:471)
	at sci.impl.interpreter$eval_special_call.invoke(interpreter.cljc:469)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:509)
	at sci.impl.interpreter$eval_call.invoke(interpreter.cljc:502)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:551)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:534)
	at sci.impl.interpreter$eval_try.invokeStatic(interpreter.cljc:289)
	at sci.impl.interpreter$eval_try.invoke(interpreter.cljc:284)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:552)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:534)
	at sci.impl.interpreter$eval_let.invokeStatic(interpreter.cljc:83)
	at sci.impl.interpreter$eval_let.doInvoke(interpreter.cljc:59)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:475)
	at sci.impl.interpreter$eval_special_call.invoke(interpreter.cljc:469)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:509)
	at sci.impl.interpreter$eval_call.invoke(interpreter.cljc:502)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:551)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:534)
	at sci.impl.interpreter$eval_let.invokeStatic(interpreter.cljc:83)
	at sci.impl.interpreter$eval_let.doInvoke(interpreter.cljc:59)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:475)
	at sci.impl.interpreter$eval_special_call.invoke(interpreter.cljc:469)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:509)
	at sci.impl.interpreter$eval_call.invoke(interpreter.cljc:502)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:551)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:534)
	at sci.impl.interpreter$eval_do_STAR_$fn__4374.invoke(interpreter.cljc:424)
	at sci.impl.interpreter$eval_do_STAR_.invokeStatic(interpreter.cljc:424)
	at sci.impl.interpreter$eval_do_STAR_.invoke(interpreter.cljc:421)
	at sci.impl.interpreter$eval_do.invokeStatic(interpreter.cljc:434)
	at sci.impl.interpreter$eval_do.invoke(interpreter.cljc:431)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:471)
	at sci.impl.interpreter$eval_special_call.invoke(interpreter.cljc:469)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:509)
	at sci.impl.interpreter$eval_call.invoke(interpreter.cljc:502)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:551)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:534)
	at sci.impl.interpreter$eval_try.invokeStatic(interpreter.cljc:289)
	at sci.impl.interpreter$eval_try.invoke(interpreter.cljc:284)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:552)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:534)
	at sci.impl.interpreter$eval_let.invokeStatic(interpreter.cljc:83)
	at sci.impl.interpreter$eval_let.doInvoke(interpreter.cljc:59)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:475)
	at sci.impl.interpreter$eval_special_call.invoke(interpreter.cljc:469)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:509)
	... 26 more

**Comment by retrogradeorbit** [comment]
fixed and released in v0.1.0-alpha.12.

@josesanch give that a go

**Comment by josesanch** [comment]
Works Great!! Thank you very much for this great piece of software!!! 

Just playing with it. However, It will probably replace our custom deployment system made using fabric (python 2).

**Comment by retrogradeorbit** [comment]
> However, It will probably replace our custom deployment system made using fabric (python 2).

That's fantastic!
