### ISSUE TITLE
Mac build on 19.3.1 fails with broken link error

### ISSUE THREAD

**Issue by retrogradeorbit** [epiccastle/spire#7]
```#!/bin/bash --login -eo pipefail
#make clean
make all macos-package GRAALVM=$GRAALVM_HOME

lein javac
Compiling 1 source files to /Users/distiller/project/target/default/classes
mkdir -p target/jni
javah -o target/jni/SpireUtils.h -cp target/default/classes SpireUtils
cc -I/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/include -I/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/include/darwin -Itarget/jni -dynamiclib -undefined suppress -flat_namespace src/c/SpireUtils.c -o target/jni/libspire.dylib -fPIC
cp target/jni/libspire.dylib ./
mkdir -p resources
cp target/jni/libspire.dylib ./resources/
make copy-libs-to-resource
cp /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/sunec.lib resources
cp: /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/sunec.lib: No such file or directory
make[1]: [copy-libs-to-resource] Error 1 (ignored)
cp /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/bin/sunec.dll resources
cp: /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/bin/sunec.dll: No such file or directory
make[1]: [copy-libs-to-resource] Error 1 (ignored)
cp /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libsunec.dylib resources
cp /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/amd64/libsunec.so resources
cp: /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/amd64/libsunec.so: No such file or directory
make[1]: [copy-libs-to-resource] Error 1 (ignored)
GRAALVM_HOME=/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home lein uberjar
Compiling 1 source files to /Users/distiller/project/target/uberjar/classes
Compiling spire.compare
Compiling spire.config
Compiling spire.core
Compiling spire.facts
Compiling spire.known-hosts
Compiling spire.local
Compiling spire.module.apt
Compiling spire.module.apt-repo
Compiling spire.module.attrs
Compiling spire.module.authorized-keys
Compiling spire.module.copy
Compiling spire.module.download
Compiling spire.module.get-file
Compiling spire.module.group
Compiling spire.module.line-in-file
Compiling spire.module.pkg
Compiling spire.module.service
Compiling spire.module.shell
Compiling spire.module.sysctl
Compiling spire.module.upload
Compiling spire.module.user
Compiling spire.namespaces
Compiling spire.nio
Compiling spire.output
Compiling spire.pack
Compiling spire.probe
Compiling spire.remote
Compiling spire.scp
Compiling spire.selmer
Compiling spire.ssh
Compiling spire.ssh-agent
Compiling spire.state
Compiling spire.system
Compiling spire.transfer
Compiling spire.transport
Compiling spire.utils
Created /Users/distiller/project/target/uberjar/spire-0.1.0-SNAPSHOT.jar
Created /Users/distiller/project/target/uberjar/spire-0.1.0-SNAPSHOT-standalone.jar
mkdir build
/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/bin/native-image \
		-jar target/uberjar/spire-0.1.0-SNAPSHOT-standalone.jar \
		-H:Name=build/spire \
		-H:+ReportExceptionStackTraces \
		-J-Dclojure.spec.skip-macros=true \
		-J-Dclojure.compiler.direct-linking=true \
		-H:ConfigurationFileDirectories=graal-configs/ \
		--initialize-at-build-time \
		--initialize-at-run-time=com.jcraft.jsch.PortWatcher \
		-H:Log=registerResource: \
		-H:EnableURLProtocols=http,https \
		--verbose \
		--allow-incomplete-classpath \
		--no-fallback \
		--no-server \
		"-J-Xmx6g"
Executing [
/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/bin/java \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-d64 \
-XX:-UseJVMCIClassLoader \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx6871947672 \
-Duser.country=US \
-Duser.language=en \
-Dorg.graalvm.version=19.3.1 \
-Dorg.graalvm.config=CE \
-Dcom.oracle.graalvm.isaot=true \
-Djvmci.class.path.append=/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/jvmci/graal.jar \
-javaagent:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/builder/svm.jar \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-Dclojure.spec.skip-macros=true \
-Dclojure.compiler.direct-linking=true \
-Xmx6g \
-Xbootclasspath/a:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/boot/graal-sdk.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/boot/graaljs-scriptengine.jar \
-cp \
/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/builder/graal-llvm.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/builder/javacpp-shadowed.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/builder/llvm-platform-specific-shadowed.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/builder/llvm-wrapper-shadowed.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/builder/objectfile.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/builder/pointsto.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/builder/svm-llvm.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/builder/svm.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/jvmci/graal-management.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/jvmci/graal.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/jvmci/jvmci-api.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/jvmci/jvmci-hotspot.jar \
com.oracle.svm.hosted.NativeImageGeneratorRunner \
-imagecp \
/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/boot/graal-sdk.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/boot/graaljs-scriptengine.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/builder/graal-llvm.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/builder/javacpp-shadowed.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/builder/llvm-platform-specific-shadowed.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/builder/llvm-wrapper-shadowed.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/builder/objectfile.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/builder/pointsto.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/builder/svm-llvm.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/builder/svm.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/jvmci/graal-management.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/jvmci/graal.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/jvmci/jvmci-api.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/jvmci/jvmci-hotspot.jar:/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/library-support.jar:/Users/distiller/project/target/uberjar/spire-0.1.0-SNAPSHOT-standalone.jar \
-H:Path=/Users/distiller/project \
-H:Class=spire.core \
-H:+ReportExceptionStackTraces \
-H:ConfigurationFileDirectories=graal-configs/ \
-H:ClassInitialization=:build_time \
-H:ClassInitialization=com.jcraft.jsch.PortWatcher:run_time \
-H:Log=registerResource: \

-H:EnableURLProtocols=http,https \
-H:+AllowIncompleteClasspath \
-H:FallbackThreshold=0 \
-H:CLibraryPath=/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64 \
-H:Name=build/spire
]
[build/spire:3081]    classlist:   6,546.48 ms
[build/spire:3081]        (cap):   2,089.59 ms
[build/spire:3081]        setup:   3,876.79 ms
[Use -Dgraal.LogFile=<path> to redirect Graal log output to a file.]
[thread:17] scope: ForkJoinPool-4-worker-1
  [thread:17] scope: ForkJoinPool-4-worker-1.registerResource
  ServiceLoaderFeature: registerResource: META-INF/services/java.nio.file.spi.FileSystemProvider
  [thread:17] scope: ForkJoinPool-4-worker-1.registerResource
  ServiceLoaderFeature: registerResource: META-INF/services/com.fasterxml.jackson.core.JsonFactory
  [thread:17] scope: ForkJoinPool-4-worker-1.registerResource
  Resources have been added by ServiceLoaderFeature. Automatic registration can be disabled with -H:-UseServiceLoaderFeature
  [thread:17] scope: ForkJoinPool-4-worker-1.registerResource
  ResourcesFeature: registerResource: libspire.dylib
  [thread:17] scope: ForkJoinPool-4-worker-1.registerResource
  ResourcesFeature: registerResource: libsunec.dylib
  [thread:17] scope: ForkJoinPool-4-worker-1.registerResource
  ServiceLoaderFeature: registerResource: META-INF/services/sun.net.spi.nameservice.NameServiceDescriptor
  [thread:17] scope: ForkJoinPool-4-worker-1.registerResource
  Resources have been added by ServiceLoaderFeature. Automatic registration can be disabled with -H:-UseServiceLoaderFeature
[build/spire:3081]   (typeflow):  51,182.71 ms
[build/spire:3081]    (objects):  34,122.13 ms
[build/spire:3081]   (features):   1,996.41 ms
[build/spire:3081]     analysis:  89,031.51 ms
[build/spire:3081]     (clinit):     765.72 ms
[build/spire:3081]     universe:   2,032.98 ms
[build/spire:3081]      (parse):   5,990.68 ms
[build/spire:3081]     (inline):   7,912.20 ms
[build/spire:3081]    (compile):  39,372.97 ms
[build/spire:3081]      compile:  56,092.23 ms
[build/spire:3081]        image:   5,131.30 ms
[build/spire:3081]        write:     938.27 ms
Fatal error: java.lang.RuntimeException: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 1

Running command: cc -v -o /Users/distiller/project/build/spire -Wl,-no_compact_unwind -Wl,-exported_symbols_list -Wl,/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/SVM-3653938336852450420/exported_symbols.list -Wl,-x -arch x86_64 -L/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/SVM-3653938336852450420 -L/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib -L/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64 /var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/SVM-3653938336852450420/build/spire.o /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libzip.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libnet.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libjava.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libnio.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libsunec.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libsunec.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libffi.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/liblibchelper.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libjvm.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libstrictmath.a -lstdc++ -lm -Wl,-framework,CoreFoundation -lpthread -ldl -lz

Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode-9.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode-9.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -lto_library /Applications/Xcode-9.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib -dynamic -arch x86_64 -macosx_version_min 10.12.0 -o /Users/distiller/project/build/spire -L/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/SVM-3653938336852450420 -L/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib -L/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64 -no_compact_unwind -exported_symbols_list /var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/SVM-3653938336852450420/exported_symbols.list -x /var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/SVM-3653938336852450420/build/spire.o /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libzip.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libnet.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libjava.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libnio.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libsunec.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libsunec.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libffi.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/liblibchelper.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libjvm.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libstrictmath.a -lc++ -lm -framework CoreFoundation -lpthread -ldl -lz -lSystem /Applications/Xcode-9.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture x86_64:
  "_VerifyClassname", referenced from:
      _Java_sun_misc_URLClassPath_knownToNotExist0 in libjava.a(URLClassPath.o)
      _Java_java_lang_ClassLoader_findBootstrapClass in libjava.a(ClassLoader.o)
  "_VerifyFixClassname", referenced from:
      _Java_sun_misc_URLClassPath_knownToNotExist0 in libjava.a(URLClassPath.o)
      _Java_java_lang_ClassLoader_findBootstrapClass in libjava.a(ClassLoader.o)
      _Java_java_lang_ClassLoader_defineClass2 in libjava.a(ClassLoader.o)
      _Java_java_lang_ClassLoader_defineClass1 in libjava.a(ClassLoader.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:462)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:315)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:454)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:115)
Caused by: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 1

Running command: cc -v -o /Users/distiller/project/build/spire -Wl,-no_compact_unwind -Wl,-exported_symbols_list -Wl,/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/SVM-3653938336852450420/exported_symbols.list -Wl,-x -arch x86_64 -L/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/SVM-3653938336852450420 -L/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib -L/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64 /var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/SVM-3653938336852450420/build/spire.o /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libzip.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libnet.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libjava.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libnio.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libsunec.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libsunec.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libffi.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/liblibchelper.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libjvm.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libstrictmath.a -lstdc++ -lm -Wl,-framework,CoreFoundation -lpthread -ldl -lz

Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode-9.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode-9.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -lto_library /Applications/Xcode-9.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib -dynamic -arch x86_64 -macosx_version_min 10.12.0 -o /Users/distiller/project/build/spire -L/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/SVM-3653938336852450420 -L/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib -L/Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64 -no_compact_unwind -exported_symbols_list /var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/SVM-3653938336852450420/exported_symbols.list -x /var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/SVM-3653938336852450420/build/spire.o /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libzip.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libnet.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libjava.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libnio.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libsunec.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libsunec.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libffi.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/liblibchelper.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libjvm.a /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libstrictmath.a -lc++ -lm -framework CoreFoundation -lpthread -ldl -lz -lSystem /Applications/Xcode-9.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture x86_64:
  "_VerifyClassname", referenced from:
      _Java_sun_misc_URLClassPath_knownToNotExist0 in libjava.a(URLClassPath.o)
      _Java_java_lang_ClassLoader_findBootstrapClass in libjava.a(ClassLoader.o)
  "_VerifyFixClassname", referenced from:
      _Java_sun_misc_URLClassPath_knownToNotExist0 in libjava.a(URLClassPath.o)
      _Java_java_lang_ClassLoader_findBootstrapClass in libjava.a(ClassLoader.o)
      _Java_java_lang_ClassLoader_defineClass2 in libjava.a(ClassLoader.o)
      _Java_java_lang_ClassLoader_defineClass1 in libjava.a(ClassLoader.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

	at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:388)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:652)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1482)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1260)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1222)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1181)
make: *** [build/spire] Error 1
```

**Comment by retrogradeorbit** [comment]
https://github.com/oracle/graal/issues/1920

**Comment by retrogradeorbit** [comment]
https://github.com/oracle/graal/issues/2144

**Comment by retrogradeorbit** [comment]
mac version needs to be build against 20.1.0-dev
