### ISSUE TITLE
Consume as Java Library

### ISSUE THREAD

**Issue by cartesian-theatrics** [epiccastle/spire#90]
Hello,

This is a really neat library! It's been very useful, thanks for the releasing! Is there any plans to release a version that can be consumed as a java/clojure library? I'd like to be able to do something like this:
```clojure
user=> (require '[spire.module.shell :refer [shell]])
nil
user=> (require '[spire.transfer :refer [ssh]])
nil
user=> (ssh "username@sandbox" (shell {:cmd "echo hello"}))
Syntax error compiling at (REPL:1:1).
No such var: spire.transfer/ssh-line
```
but doesn't seem to be possible using the compiled jar. Is this not an intended use case? 

Thanks,
John C.

**Comment by retrogradeorbit** [comment]
The intention was to support usage in the JVM. It's lacking tests and it has been some time since I tested this. Will have a look.

**Comment by retrogradeorbit** [comment]
`spire.transfer` is a very old implementation that needs to be removed. The actuall `ssh` is in `spire.transport`. You will also need to load the `.so` or `.dynlib` library for you platform before connection.

```
$ lein repl
nREPL server started on port 45669 on host 127.0.0.1 - nrepl://127.0.0.1:45669
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by mranderson049.orchard.v0v4v0.dynapath.v0v2v5.dynapath.defaults$eval28109$fn__28110 to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of mranderson049.orchard.v0v4v0.dynapath.v0v2v5.dynapath.defaults$eval28109$fn__28110
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
REPL-y 0.4.4, nREPL 0.6.0
Clojure 1.10.2-alpha1
OpenJDK 64-Bit Server VM 11.0.7+10-post-Ubuntu-2ubuntu218.04
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

spire.core=> (require '[spire.module.shell :refer [shell]])
nil
spire.core=> (require '[spire.transport :refer [ssh]])
nil
spire.core=> (clojure.lang.RT/loadLibrary "spire")
nil
spire.core=> (ssh "crispin@epiccastle.io" (shell {:cmd "echo hello"}))
{:exit 0, :out "hello\n", :err "", :out-lines ["hello"], :result :ok}
```

**Comment by cartesian-theatrics** [comment]
Aha, works. Thanks!

**Comment by cartesian-theatrics** [comment]
Probably asking a bit much, but as a follow up I trust tried building a native image that includes spire, copying all the flags in the Makefile. It build successfully but unfortunately it doesn't seem to work.
```
➜  native-image git:(develop) ✗ ./core 
Exception in thread "main" com.jcraft.jsch.JSchException: Algorithm negotiation fail
	at com.jcraft.jsch.Session.receive_kexinit(Session.java:590)
	at com.jcraft.jsch.Session.connect(Session.java:320)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at spire.transport$connect.invokeStatic(transport.clj:31)
	at spire.transport$open_connection$fn__6843.invoke(transport.clj:52)
	at clojure.core$update.invokeStatic(core.clj:6196)
	at clojure.core$update.invoke(core.clj:6188)
	at clojure.lang.Atom.swap(Atom.java:65)
	at clojure.core$swap_BANG_.invokeStatic(core.clj:2354)
	at spire.transport$open_connection.invokeStatic(transport.clj:47)
	at core$_main.invokeStatic(core.clj:9)
	at core$_main.doInvoke(core.clj:9)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at core.main(Unknown Source)
```
That was after adding `com.jcraft.jsch.jce.Random` to the reflection list. It's not clear to me how sci is able to work with `com.jcraft.jsch.Session`.

**Comment by retrogradeorbit** [comment]
`com.jcraft.jsch.jce.Random`is in the reflection config used when building spire: https://github.com/epiccastle/spire/blob/master/graal-configs/reflect-config.json#L57

Try initialising the graal runtime environment the way spire does. https://github.com/epiccastle/spire/blob/master/src/clj/spire/core.clj#L29-L39

This will load the C library that is bundled in the resources (you will need to bundle this in your resources with the graal build) https://github.com/epiccastle/spire/blob/master/graal-configs/resource-config.json#L3-L4

If you are authenticating using your ssh-agent, then it will not be able to authenticate unless the shared C library is loaded at runtime. This may be the problem you are seeing if it works as shown when running under spire itself.

You could initialise by calling `spire.core/initialise` routine with an empty hashmap to initialise (or with a hashmap `{:debug-ssh true}` to debug why your algorithm negotiation is failing if it continues to do so). 

To set it up manually you would do something like:

```clojure
(ns core
  (:require
   [spire.core]
   [spire.config :as config]
   [spire.module.shell :refer [shell]]
   [spire.transport :refer [ssh]])
  (:import [com.jcraft.jsch JSch Logger])
  (:gen-class))

(defn -main [& args]
  (config/init!) ;; when running under graal, extracts the shared library to users home directory and sets up the java library path. You will need to have the .so or .dynlib file bundled in your resources for this extraction to work.
  (clojure.lang.RT/loadLibrary "spire") ;; load the C library
  (ssh "brain@sandbox" (shell {:cmd "echo 'hello'"})))
```

**Comment by cartesian-theatrics** [comment]
Thanks for all you help. I think it's closer but still not working yet:
```
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Invoke with MethodHandle argument could not be reduced to at most a single call or single field access. The method handle must be a compile time constant, e.g., be loaded from a `static final` field. Method that contains the method handle invocation: java.lang.invoke.Invokers$Holder.invoke_MT(Object, Object, Object, Object)
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:86)
	at clojure.lang.Reflector.canAccess(Reflector.java:49)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:156)
	at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:332)
	at spire.known_hosts$hash_hostname.invokeStatic(known_hosts.clj:100)
	at spire.known_hosts$host_matches_QMARK_.invokeStatic(known_hosts.clj:107)
	at spire.known_hosts$any_host_matches_QMARK_$fn__6735.invoke(known_hosts.clj:118)
	at clojure.core$some.invokeStatic(core.clj:2701)
	at spire.known_hosts$any_host_matches_QMARK_.invokeStatic(known_hosts.clj:117)
	at spire.known_hosts$find_matching_host_entries$fn__6739.invoke(known_hosts.clj:121)
	at clojure.core$filter$fn__5893.invoke(core.clj:2817)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5402.invokeStatic(core.clj:137)
	at clojure.core$filter$fn__5893.invoke(core.clj:2809)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.LazySeq.first(LazySeq.java:73)
	at clojure.lang.RT.first(RT.java:692)
	at clojure.core$first__5387.invokeStatic(core.clj:55)
	at spire.known_hosts$make_host_key_repository$fn__6784.invoke(known_hosts.clj:216)
	at spire.known_hosts.proxy$java.lang.Object$HostKeyRepository$cc0cb7b.check(Unknown Source)
	at com.jcraft.jsch.Session.checkHost(Session.java:740)
	at com.jcraft.jsch.Session.connect(Session.java:345)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at spire.transport$connect.invokeStatic(transport.clj:31)
	at spire.transport$open_connection$fn__6843.invoke(transport.clj:52)
	at clojure.core$update.invokeStatic(core.clj:6196)
	at clojure.core$update.invoke(core.clj:6188)
	at clojure.lang.Atom.swap(Atom.java:65)
	at clojure.core$swap_BANG_.invokeStatic(core.clj:2354)
	at spire.transport$open_connection.invokeStatic(transport.clj:47)
	at core$_main.invokeStatic(core.clj:14)
	at core$_main.doInvoke(core.clj:10)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at core.main(Unknown Source)
```

**Comment by cartesian-theatrics** [comment]
Okay, I got it to mostly work using Borkdude's `clj-reflector-graal-java11-fix`. The only issue I'm facing now is that the logger doesn't seem to work. Nothing is printed to stdout. I put up an example project here:
https://github.com/cartesian-theatrics/spire-native-image-example

**Comment by cartesian-theatrics** [comment]
Okay, got it working! Just needed the `puget/cprint`. Thanks for all your help. Now ready to implement basic lifecycle management on top of spire :) 

Feel free to close.

**Comment by jeroenvandijk** [comment]
@retrogradeorbit I had to add `(require 'spire.output.core)` to your [instructions](https://github.com/epiccastle/spire/issues/90#issuecomment-646918772) or I'm getting:
```
Syntax error (ClassNotFoundException) compiling at (/private/var/folders/ck/9zqvs0zx5vsf2bc7rvv1pwc40000gn/T/form-init14248799307276523803.clj:1:30).
spire.output.core
```

Thus the following works for me:
```clojure
lein repl
(require '[spire.transport :refer [ssh]])
(require '[spire.module.shell :refer [shell]])
(clojure.lang.RT/loadLibrary "spire")
(require 'spire.output.core)
(ssh "crispin@epiccastle.io" (shell {:cmd "echo hello"}))
```

**Comment by jeroenvandijk** [comment]
I alos had to add `(require 'spire.core)` to require all `print-form` methods

And I had to use host-config and not host string, something like this:
```clojure
(ssh {:host-string "ec2-user@***"
      :identity "***
      :passphrase "***"
      :accept-host-key true}
     (shell {:cmd "echo 'hello'"}))
```
